// <auto-generated>
#nullable enable

using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlTypes;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;

namespace Efrpg.V9IdenticalMerged
{
    #region Database context interface

    public interface IEfrpgTestDbContext : IDisposable
    {

        int SaveChanges();
        int SaveChanges(bool acceptAllChangesOnSuccess);
        Task<int> SaveChangesAsync(CancellationToken cancellationToken = default(CancellationToken));
        Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default(CancellationToken));
        DatabaseFacade Database { get; }
        DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string? ToString();

        EntityEntry Add(object entity);
        EntityEntry<TEntity> Add<TEntity>(TEntity entity) where TEntity : class;
        Task AddRangeAsync(params object[] entities);
        Task AddRangeAsync(IEnumerable<object> entities, CancellationToken cancellationToken = default);
        ValueTask<EntityEntry<TEntity>> AddAsync<TEntity>(TEntity entity, CancellationToken cancellationToken = default) where TEntity : class;
        ValueTask<EntityEntry> AddAsync(object entity, CancellationToken cancellationToken = default);
        void AddRange(IEnumerable<object> entities);
        void AddRange(params object[] entities);

        EntityEntry Attach(object entity);
        EntityEntry<TEntity> Attach<TEntity>(TEntity entity) where TEntity : class;
        void AttachRange(IEnumerable<object> entities);
        void AttachRange(params object[] entities);

        EntityEntry Entry(object entity);
        EntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;

        TEntity? Find<TEntity>(params object?[]? keyValues) where TEntity : class;
        ValueTask<TEntity?> FindAsync<TEntity>(object?[]? keyValues, CancellationToken cancellationToken) where TEntity : class;
        ValueTask<TEntity?> FindAsync<TEntity>(params object?[]? keyValues) where TEntity : class;
        ValueTask<object?> FindAsync(Type entityType, object?[]? keyValues, CancellationToken cancellationToken);
        ValueTask<object?> FindAsync(Type entityType, params object?[]? keyValues);
        object? Find(Type entityType, params object?[]? keyValues);

        EntityEntry Remove(object entity);
        EntityEntry<TEntity> Remove<TEntity>(TEntity entity) where TEntity : class;
        void RemoveRange(IEnumerable<object> entities);
        void RemoveRange(params object[] entities);

        EntityEntry Update(object entity);
        EntityEntry<TEntity> Update<TEntity>(TEntity entity) where TEntity : class;
        void UpdateRange(IEnumerable<object> entities);
        void UpdateRange(params object[] entities);

        IQueryable<TResult> FromExpression<TResult> (Expression<Func<IQueryable<TResult>>> expression);

        // Stored Procedures
        List<StpMultipleIdenticalResultsReturnModel> StpMultipleIdenticalResults(int? someVar);
        List<StpMultipleIdenticalResultsReturnModel> StpMultipleIdenticalResults(int? someVar, out int procResult);
        Task<List<StpMultipleIdenticalResultsReturnModel>> StpMultipleIdenticalResultsAsync(int? someVar, CancellationToken cancellationToken = default(CancellationToken));

    }

    #endregion

    #region Database context

    public class EfrpgTestDbContext : DbContext, IEfrpgTestDbContext
    {
        public EfrpgTestDbContext()
        {
        }

        public EfrpgTestDbContext(DbContextOptions<EfrpgTestDbContext> options)
            : base(options)
        {
        }

        protected EfrpgTestDbContext(DbContextOptions options)
            : base(options)
        {
        }


        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(@"Data Source=(local);Initial Catalog=EfrpgTest;Integrated Security=True;Encrypt=false;TrustServerCertificate=true;Application Name=Generator");
                optionsBuilder.UseLazyLoadingProxies();
            }
        }

        public bool IsSqlParameterNull(SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == DBNull.Value);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<StpMultipleIdenticalResultsReturnModel>().HasNoKey();
        }


        // Stored Procedures
        public List<StpMultipleIdenticalResultsReturnModel> StpMultipleIdenticalResults(int? someVar = null)
        {
            int procResult;
            return StpMultipleIdenticalResults(someVar, out procResult);
        }

        public List<StpMultipleIdenticalResultsReturnModel> StpMultipleIdenticalResults(int? someVar, out int procResult)
        {
            var someVarParam = new SqlParameter { ParameterName = "@someVar", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Input, Value = someVar.GetValueOrDefault(), Precision = 10, Scale = 0 };
            if (!someVar.HasValue)
                someVarParam.Value = DBNull.Value;

            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };
            const string sqlCommand = "EXEC @procResult = [dbo].[stp_multiple_identical_results] @someVar";
            var procResultData = Set<StpMultipleIdenticalResultsReturnModel>()
                .FromSqlRaw(sqlCommand, someVarParam, procResultParam)
                .ToList();

            procResult = (int) procResultParam.Value;
            return procResultData;
        }

        public async Task<List<StpMultipleIdenticalResultsReturnModel>> StpMultipleIdenticalResultsAsync(int? someVar = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            var someVarParam = new SqlParameter { ParameterName = "@someVar", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Input, Value = someVar.GetValueOrDefault(), Precision = 10, Scale = 0 };
            if (!someVar.HasValue)
                someVarParam.Value = DBNull.Value;

            const string sqlCommand = "EXEC [dbo].[stp_multiple_identical_results] @someVar";
            var procResultData = await Set<StpMultipleIdenticalResultsReturnModel>()
                .FromSqlRaw(sqlCommand, someVarParam)
                .ToListAsync(cancellationToken);

            return procResultData;
        }

    }

    #endregion

    #region Database context factory

    public class EfrpgTestDbContextFactory : IDesignTimeDbContextFactory<EfrpgTestDbContext>
    {
        private readonly DbContextOptions<EfrpgTestDbContext>? Options;

        public EfrpgTestDbContextFactory()
        {
            Options = null;
        }

        public EfrpgTestDbContextFactory(DbContextOptions<EfrpgTestDbContext> options)
        {
            Options = options;
        }

        public EfrpgTestDbContext CreateDbContext(string[] args)
        {
            return new EfrpgTestDbContext();
        }

        public EfrpgTestDbContext CreateDbContext()
        {
            return Options != null ? new EfrpgTestDbContext(Options) : new EfrpgTestDbContext();
        }

        public EfrpgTestDbContext CreateDbContext(DbContextOptions<EfrpgTestDbContext> options)
        {
            return options == null
                ? new EfrpgTestDbContext()
                : new EfrpgTestDbContext(options);
        }
    }

    #endregion

    #region Stored procedure return models

    public class StpMultipleIdenticalResultsReturnModel
    {
        public int Id { get; set; }
        public string Name { get; set; } = null!;
    }


    #endregion

}
// </auto-generated>
