// <auto-generated>

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using Tester.Integration.EFCore8.Single_context_many_files.Configuration;
using Tester.Integration.EFCore8.Single_context_many_files.Contexts;
using Tester.Integration.EFCore8.Single_context_many_files.Interfaces;

namespace Tester.Integration.EFCore8.Single_context_many_files.Entities
{
    // ExpressionDefault
    public class ExpressionDefault
    {
        public int Id { get; set; } // Id (Primary key)
        public string ChangedBy { get; set; } // ChangedBy (length: 128)
        public string AppName { get; set; } // AppName (length: 128)
        public string DbUser { get; set; } // DbUser (length: 128)
        public string CreatedText { get; set; } // CreatedText (length: 30)
        public DateTime DueAt { get; set; } // DueAt
        public DateTime CreatedAt { get; set; } // CreatedAt
        public string Token { get; set; } // Token (length: 36)
        public string LiteralText { get; set; } // LiteralText (length: 20)
        public string NumberText { get; set; } // NumberText (length: 10)

        public ExpressionDefault()
        {
            CreatedAt = DateTime.UtcNow;
            Token = Guid.NewGuid().ToString();
            LiteralText = "fallback";
            NumberText = "0";
        }
    }

}
// </auto-generated>
