// <auto-generated>

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using Tester.Integration.EFCore8.Single_context_many_files.Configuration;
using Tester.Integration.EFCore8.Single_context_many_files.Contexts;
using Tester.Integration.EFCore8.Single_context_many_files.Interfaces;

namespace Tester.Integration.EFCore8.Single_context_many_files.Entities
{
    // StringDefaultEscaping
    public class StringDefaultEscaping
    {
        public int Id { get; set; } // Id (Primary key)
        public string QuoteOnly { get; set; } // QuoteOnly (length: 30)
        public string BackslashOnly { get; set; } // BackslashOnly (length: 30)
        public string BackslashAndQuote { get; set; } // BackslashAndQuote (length: 30)
        public string QuoteThenBackslash { get; set; } // QuoteThenBackslash (length: 30)

        public StringDefaultEscaping()
        {
            QuoteOnly = "say \"hi\"";
            BackslashOnly = @"C:\Temp";
            BackslashAndQuote = @"C:\Temp\say ""hi""";
            QuoteThenBackslash = @"""quoted""\";
        }
    }

}
// </auto-generated>
