// <auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Text.Json.Serialization;
using Tester.Integration.EFCore8.Single_context_many_files.Contexts;
using Tester.Integration.EFCore8.Single_context_many_files.Entities;
using Tester.Integration.EFCore8.Single_context_many_files.Interfaces;

namespace Tester.Integration.EFCore8.Single_context_many_files.Configuration
{
    // ExpressionDefault
    public class ExpressionDefaultConfiguration : IEntityTypeConfiguration<ExpressionDefault>
    {
        public void Configure(EntityTypeBuilder<ExpressionDefault> builder)
        {
            builder.ToTable("ExpressionDefault", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_ExpressionDefault").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.ChangedBy).HasColumnName(@"ChangedBy").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128).HasDefaultValueSql(@"suser_sname()");
            builder.Property(x => x.AppName).HasColumnName(@"AppName").HasColumnType("nvarchar(128)").IsRequired(false).HasMaxLength(128).HasDefaultValueSql(@"app_name()");
            builder.Property(x => x.DbUser).HasColumnName(@"DbUser").HasColumnType("nvarchar(128)").IsRequired(false).HasMaxLength(128).HasDefaultValueSql(@"user_name()");
            builder.Property(x => x.CreatedText).HasColumnName(@"CreatedText").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30).HasDefaultValueSql(@"CONVERT([varchar](30),getdate(),(126))");
            builder.Property(x => x.DueAt).HasColumnName(@"DueAt").HasColumnType("datetime2").IsRequired().HasDefaultValueSql(@"dateadd(day,(30),sysutcdatetime())");
            builder.Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetime2").IsRequired();
            builder.Property(x => x.Token).HasColumnName(@"Token").HasColumnType("nvarchar(36)").IsRequired().HasMaxLength(36);
            builder.Property(x => x.LiteralText).HasColumnName(@"LiteralText").HasColumnType("nvarchar(20)").IsRequired().HasMaxLength(20);
            builder.Property(x => x.NumberText).HasColumnName(@"NumberText").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10);
        }
    }

}
// </auto-generated>
