// <auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Text.Json.Serialization;
using Tester.Integration.EFCore8.Single_context_many_files.Contexts;
using Tester.Integration.EFCore8.Single_context_many_files.Entities;
using Tester.Integration.EFCore8.Single_context_many_files.Interfaces;

namespace Tester.Integration.EFCore8.Single_context_many_files.Configuration
{
    // StringDefaultEscaping
    public class StringDefaultEscapingConfiguration : IEntityTypeConfiguration<StringDefaultEscaping>
    {
        public void Configure(EntityTypeBuilder<StringDefaultEscaping> builder)
        {
            builder.ToTable("StringDefaultEscaping", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_StringDefaultEscaping").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.QuoteOnly).HasColumnName(@"QuoteOnly").HasColumnType("varchar(30)").IsRequired().IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.BackslashOnly).HasColumnName(@"BackslashOnly").HasColumnType("varchar(30)").IsRequired().IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.BackslashAndQuote).HasColumnName(@"BackslashAndQuote").HasColumnType("varchar(30)").IsRequired().IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.QuoteThenBackslash).HasColumnName(@"QuoteThenBackslash").HasColumnType("varchar(30)").IsRequired().IsUnicode(false).HasMaxLength(30);
        }
    }

}
// </auto-generated>
