// <auto-generated>
// ReSharper disable All

using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlTypes;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;

namespace RP
{
    #region Database context interface

    #nullable enable annotations
    public interface IAzureContext : IDisposable
    {
        DbSet<Country> Countries { get; set; } // Country
        DbSet<NotificationType> NotificationTypes { get; set; } // NotificationType
        DbSet<TestingEfCore10> TestingEfCore10 { get; set; } // Testing_EfCore10

        int SaveChanges();
        int SaveChanges(bool acceptAllChangesOnSuccess);
        Task<int> SaveChangesAsync(CancellationToken cancellationToken = default(CancellationToken));
        Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default(CancellationToken));
        DatabaseFacade Database { get; }
        DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string? ToString();

        EntityEntry Add(object entity);
        EntityEntry<TEntity> Add<TEntity>(TEntity entity) where TEntity : class;
        Task AddRangeAsync(params object[] entities);
        Task AddRangeAsync(IEnumerable<object> entities, CancellationToken cancellationToken = default);
        ValueTask<EntityEntry<TEntity>> AddAsync<TEntity>(TEntity entity, CancellationToken cancellationToken = default) where TEntity : class;
        ValueTask<EntityEntry> AddAsync(object entity, CancellationToken cancellationToken = default);
        void AddRange(IEnumerable<object> entities);
        void AddRange(params object[] entities);

        EntityEntry Attach(object entity);
        EntityEntry<TEntity> Attach<TEntity>(TEntity entity) where TEntity : class;
        void AttachRange(IEnumerable<object> entities);
        void AttachRange(params object[] entities);

        EntityEntry Entry(object entity);
        EntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;

        TEntity? Find<TEntity>(params object?[]? keyValues) where TEntity : class;
        ValueTask<TEntity?> FindAsync<TEntity>(object?[]? keyValues, CancellationToken cancellationToken) where TEntity : class;
        ValueTask<TEntity?> FindAsync<TEntity>(params object?[]? keyValues) where TEntity : class;
        ValueTask<object?> FindAsync(Type entityType, object?[]? keyValues, CancellationToken cancellationToken);
        ValueTask<object?> FindAsync(Type entityType, params object?[]? keyValues);
        object? Find(Type entityType, params object?[]? keyValues);

        EntityEntry Remove(object entity);
        EntityEntry<TEntity> Remove<TEntity>(TEntity entity) where TEntity : class;
        void RemoveRange(IEnumerable<object> entities);
        void RemoveRange(params object[] entities);

        EntityEntry Update(object entity);
        EntityEntry<TEntity> Update<TEntity>(TEntity entity) where TEntity : class;
        void UpdateRange(IEnumerable<object> entities);
        void UpdateRange(params object[] entities);

        IQueryable<TResult> FromExpression<TResult> (Expression<Func<IQueryable<TResult>>> expression);
    }
    #nullable disable

    #endregion

    #region Database context

    #nullable enable annotations
    public class AzureContext : DbContext, IAzureContext
    {
        public AzureContext()
        {
        }

        public AzureContext(DbContextOptions<AzureContext> options)
            : base(options)
        {
        }

        protected AzureContext(DbContextOptions options)
            : base(options)
        {
        }

        public DbSet<Country> Countries { get; set; } // Country
        public DbSet<NotificationType> NotificationTypes { get; set; } // NotificationType
        public DbSet<TestingEfCore10> TestingEfCore10 { get; set; } // Testing_EfCore10

        public bool IsSqlParameterNull(SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == DBNull.Value);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.ApplyConfiguration(new CountryConfiguration());
            modelBuilder.ApplyConfiguration(new NotificationTypeConfiguration());
            modelBuilder.ApplyConfiguration(new TestingEfCore10Configuration());
        }

    }
    #nullable disable

    #endregion

    #region Database context factory

    #nullable enable annotations
    public class AzureContextFactory : IDesignTimeDbContextFactory<AzureContext>
    {
        private readonly DbContextOptions<AzureContext>? Options;

        public AzureContextFactory()
        {
            Options = null;
        }

        public AzureContextFactory(DbContextOptions<AzureContext> options)
        {
            Options = options;
        }

        public AzureContext CreateDbContext(string[] args)
        {
            return new AzureContext();
        }

        public AzureContext CreateDbContext()
        {
            return Options != null ? new AzureContext(Options) : new AzureContext();
        }

        public AzureContext CreateDbContext(DbContextOptions<AzureContext> options)
        {
            return options == null
                ? new AzureContext()
                : new AzureContext(options);
        }
    }
    #nullable disable

    #endregion

    #region POCO classes

    // Country
    public class Country
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 100)
        public string TwoLetterIsoCode { get; set; } // TwoLetterIsoCode (length: 2)
        public string ThreeLetterIsoCode { get; set; } // ThreeLetterIsoCode (length: 3)
        public bool SubjectToVat { get; set; } // SubjectToVat
        public decimal? VatRate { get; set; } // VatRate
        public bool Published { get; set; } // Published
        public int DisplayOrder { get; set; } // DisplayOrder
        public bool InEurope { get; set; } // InEurope

        public Country()
        {
            InEurope = true;
        }
    }

    // NotificationType
    public class NotificationType
    {
        public int Id { get; set; } // Id (Primary key)
        public string Description { get; set; } // Description (length: 50)
        public bool Active { get; set; } // Active
    }

    // Testing_EfCore10
    public class TestingEfCore10
    {
        public int Id { get; set; } // Id (Primary key)
        public byte[] Embedding { get; set; } // Embedding (length: 4944)
        public string ShippingAddress { get; set; } // ShippingAddress
    }


    #endregion

    #region POCO Configuration

    // Country
    public class CountryConfiguration : IEntityTypeConfiguration<Country>
    {
        public void Configure(EntityTypeBuilder<Country> builder)
        {
            builder.ToTable("Country", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_Country").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("varchar(100)").IsRequired().IsUnicode(false).HasMaxLength(100);
            builder.Property(x => x.TwoLetterIsoCode).HasColumnName(@"TwoLetterIsoCode").HasColumnType("varchar(2)").IsRequired().IsUnicode(false).HasMaxLength(2);
            builder.Property(x => x.ThreeLetterIsoCode).HasColumnName(@"ThreeLetterIsoCode").HasColumnType("varchar(3)").IsRequired().IsUnicode(false).HasMaxLength(3);
            builder.Property(x => x.SubjectToVat).HasColumnName(@"SubjectToVat").HasColumnType("bit").IsRequired();
            builder.Property(x => x.VatRate).HasColumnName(@"VatRate").HasColumnType("decimal(9,5)").HasPrecision(9,5).IsRequired(false);
            builder.Property(x => x.Published).HasColumnName(@"Published").HasColumnType("bit").IsRequired();
            builder.Property(x => x.DisplayOrder).HasColumnName(@"DisplayOrder").HasColumnType("int").IsRequired();
            builder.Property(x => x.InEurope).HasColumnName(@"InEurope").HasColumnType("bit").IsRequired();

            builder.HasIndex(x => new { x.DisplayOrder, x.Name }).HasDatabaseName("IX_Country_DisplayOrder_Name");
        }
    }

    // NotificationType
    public class NotificationTypeConfiguration : IEntityTypeConfiguration<NotificationType>
    {
        public void Configure(EntityTypeBuilder<NotificationType> builder)
        {
            builder.ToTable("NotificationType", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_NotificationType").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("varchar(50)").IsRequired().IsUnicode(false).HasMaxLength(50);
            builder.Property(x => x.Active).HasColumnName(@"Active").HasColumnType("bit").IsRequired();
        }
    }

    // Testing_EfCore10
    public class TestingEfCore10Configuration : IEntityTypeConfiguration<TestingEfCore10>
    {
        public void Configure(EntityTypeBuilder<TestingEfCore10> builder)
        {
            builder.ToTable("Testing_EfCore10", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_Testing_EfCore10").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Embedding).HasColumnName(@"Embedding").HasColumnType("vector(1234)").IsRequired(false);
            builder.Property(x => x.ShippingAddress).HasColumnName(@"ShippingAddress").HasColumnType("json").IsRequired();
        }
    }


    #endregion

}
// </auto-generated>
